import type { Metadata } from "next";
import { Inter, Fraunces, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { LenisProvider } from "@/lib/motion/lenis-provider";
import { Nav } from "@/components/shell/nav";
import { Footer } from "@/components/shell/footer";
import { ScrollProgress } from "@/components/shell/scroll-progress";
import { RouteTransition } from "@/components/shell/route-transition";
import { InitialCurtain } from "@/components/shell/initial-curtain";
import { CustomCursor } from "@/components/shell/custom-cursor";
import { TerminalMount } from "@/components/terminal/terminal-mount";
import { JsonLd } from "@/components/seo/json-ld";
import { siteGraph } from "@/lib/seo";

// ─── Fonts ──────────────────────────────────────────────────────────────

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  display: "swap",
});

const fraunces = Fraunces({
  variable: "--font-fraunces",
  subsets: ["latin"],
  display: "swap",
  axes: ["opsz", "SOFT"],
});

const jetbrains = JetBrains_Mono({
  variable: "--font-jetbrains",
  subsets: ["latin"],
  display: "swap",
});

// ─── SEO Metadata ───────────────────────────────────────────────────────

const BASE_URL = "https://shashankdhiman.in";

export const metadata: Metadata = {
  metadataBase: new URL(BASE_URL),

  title: {
    default: "Shashank Dhiman — Full Stack Engineer",
    template: "%s · Shashank Dhiman",
  },
  description:
    "Full stack engineer specialising in real-time systems and API & backend engineering. Building systems that survive production — WebRTC, event-driven architecture, LLM integration, distributed infrastructure.",

  keywords: [
    "Shashank Dhiman",
    "full stack engineer",
    "backend engineer",
    "ai engineer",
    "real-time systems",
    "LLM integration",
    "OpenRouter",
    "MediaPipe",
    "Node.js",
    "WebSocket",
    "distributed systems",
    "India",
    "software engineer",
    "portfolio",
  ],

  authors: [{ name: "Shashank Dhiman", url: BASE_URL }],
  creator: "Shashank Dhiman",
  publisher: "Shashank Dhiman",

  // ── Canonical & alternates ──────────────────────────────────────────
  // NOTE: no site-wide canonical here. Metadata is inherited as-is, so a
  // root canonical would mark every sub-page as a duplicate of the
  // homepage. Each page declares its own via `alternates.canonical`.

  // ── Open Graph ──────────────────────────────────────────────────────
  openGraph: {
    type: "website",
    url: BASE_URL,
    siteName: "Shashank Dhiman",
    title: "Shashank Dhiman — Full Stack Engineer",
    description:
      "Full stack engineer — real-time systems, APIs, LLM integration. Building things that survive production.",
    images: [
      {
        url: "/hero/portrait-halftone2.png",
        width: 1200,
        height: 630,
        alt: "Shashank Dhiman — Full Stack Engineer",
      },
    ],
    locale: "en_IN",
  },

  // ── Twitter / X card ────────────────────────────────────────────────
  twitter: {
    card: "summary_large_image",
    title: "Shashank Dhiman — Full Stack Engineer",
    description:
      "Full stack engineer — real-time systems, APIs, LLM integration. Building things that survive production.",
    images: ["/hero/portrait-halftone2.png"],
  },

  // ── Robots ──────────────────────────────────────────────────────────
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },

  // ── Icons ────────────────────────────────────────────────────────────
  // New brand mark, generated by realfavicongenerator. Files live at the
  // /public/ root (Next.js App Router serves them at the URL root). Order
  // matters: PNG listed first so size-conscious browsers pick the 16 KB
  // raster instead of the heavier vector. The SVG stays declared for
  // browsers that prefer sharp-scaling vectors at any tab size.
  // Next.js auto-serves /public/favicon.ico at /favicon.ico — no need to
  // declare it explicitly.
  icons: {
    icon: [
      { url: "/hero/favicon.png", type: "image/png" },
      { url: "/icon0.svg", type: "image/svg+xml", sizes: "any" },
    ],
    apple: [
      { url: "/hero/favicon.png" },
    ],
    other: [
      { rel: "manifest", url: "/manifest.json" },
    ],
  },

  // ── Verification (add tokens once you connect Search Console) ───────
  // verification: {
  //   google: "YOUR_GOOGLE_SEARCH_CONSOLE_TOKEN",
  // },
};

// ─── Root layout ────────────────────────────────────────────────────────

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${fraunces.variable} ${jetbrains.variable}`}
      suppressHydrationWarning
    >
      <head>
        {/* Site-wide entity graph: enriched Person + WebSite, joined by
            stable @id anchors. Case-study pages add their own TechArticle
            nodes that reference these. Built in src/lib/seo.ts. */}
        <JsonLd data={siteGraph()} />
      </head>
      <body className="min-h-screen bg-paper text-ink" suppressHydrationWarning>
        <LenisProvider>
          <Nav />
          <main>{children}</main>
          <Footer />
          <ScrollProgress />
        </LenisProvider>

        {/* Vercel telemetry — page views + Web Vitals. Both inject scripts
            only in production and respect Do Not Track. Safe to leave on
            in dev (they no-op locally). */}
        <Analytics />
        <SpeedInsights />

        {/* Global route-change ceremony — two ink panels meet, sketch
            asterisk pencils in, panels split apart. */}
        <RouteTransition />

        {/* Cold-load / hard-reload welcome — panels start closed, asterisk
            pencils in, Delhi coordinates fade in, then panels open. Plays
            once per page load, then self-unmounts. */}
        <InitialCurtain />

        {/* Ink dot + trailing ring over the native cursor. Pointer-fine,
            hover-capable, motion-tolerant devices only. */}
        <CustomCursor />

        {/* Summonable command terminal (⌘K / nav chip). Overlay is lazy —
            loads only on first open. */}
        <TerminalMount />
      </body>
    </html>
  );
}
